package com.wdc.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-16T15:38:36.798+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://service.wdc.com/", name = "HelloService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloService {

    @WebMethod
    @RequestWrapper(localName = "hello", targetNamespace = "http://service.wdc.com/", className = "com.wdc.client.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://service.wdc.com/", className = "com.wdc.client.HelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "sendStudent", targetNamespace = "http://service.wdc.com/", className = "com.wdc.client.SendStudent")
    @ResponseWrapper(localName = "sendStudentResponse", targetNamespace = "http://service.wdc.com/", className = "com.wdc.client.SendStudentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.wdc.client.Student sendStudent(
        @WebParam(name = "arg0", targetNamespace = "")
        com.wdc.client.Student arg0
    );
}
