
package com.wdc.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HelloSeriveImplService", targetNamespace = "http://service.wdc.com/", wsdlLocation = "http://127.0.0.1/webservice/user?wsdl")
public class HelloSeriveImplService
    extends Service
{

    private final static URL HELLOSERIVEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HELLOSERIVEIMPLSERVICE_EXCEPTION;
    private final static QName HELLOSERIVEIMPLSERVICE_QNAME = new QName("http://service.wdc.com/", "HelloSeriveImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://127.0.0.1/webservice/user?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HELLOSERIVEIMPLSERVICE_WSDL_LOCATION = url;
        HELLOSERIVEIMPLSERVICE_EXCEPTION = e;
    }

    public HelloSeriveImplService() {
        super(__getWsdlLocation(), HELLOSERIVEIMPLSERVICE_QNAME);
    }

    public HelloSeriveImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HELLOSERIVEIMPLSERVICE_QNAME, features);
    }

    public HelloSeriveImplService(URL wsdlLocation) {
        super(wsdlLocation, HELLOSERIVEIMPLSERVICE_QNAME);
    }

    public HelloSeriveImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HELLOSERIVEIMPLSERVICE_QNAME, features);
    }

    public HelloSeriveImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloSeriveImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HelloSeriveImpl
     */
    @WebEndpoint(name = "HelloSeriveImplPort")
    public HelloSeriveImpl getHelloSeriveImplPort() {
        return super.getPort(new QName("http://service.wdc.com/", "HelloSeriveImplPort"), HelloSeriveImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloSeriveImpl
     */
    @WebEndpoint(name = "HelloSeriveImplPort")
    public HelloSeriveImpl getHelloSeriveImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.wdc.com/", "HelloSeriveImplPort"), HelloSeriveImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HELLOSERIVEIMPLSERVICE_EXCEPTION!= null) {
            throw HELLOSERIVEIMPLSERVICE_EXCEPTION;
        }
        return HELLOSERIVEIMPLSERVICE_WSDL_LOCATION;
    }

}
